#!/usr/bin/env python3
r"""
convert.py - draft a Traditional-Chinese version of the Simplified-Chinese book in /text,
using the three tables in this folder, and write it under translations/Traditional Chinese/.

Most SC->TC conversion is unambiguous, but some depends on context (干 can be 幹/乾/干;
软件 may want the regional 軟體). So the script applies its best guess and flags every
non-trivial spot with an inline mark for a human/AI to confirm or fix. The one thing it
applies SILENTLY is a single character with exactly one traditional form (这->這): it
cannot be wrong.

Tables (01 is generated by tables/build_tables.py; 02/03 are hand-maintained, cols sc,chosen):
  01_characters.csv    single char -> traditional candidate(s), concatenated, default first;
                       ambiguous=Y when >1. Large and machine-only; convert.py reads it.
  02_vocab_stable.csv  words to KEEP as standard/mainland traditional (比特币->比特幣).
  03_vocab_change.csv  words to CHANGE to another TC form (软件->軟體).
Only table a word whose source has ONE meaning. A context-dependent word (默认 = acquiesce
vs. computing-default) is left to per-spot review, not forced to one reading by a table.

Marks (one character each); the build will not compile until every mark is resolved:
  ¹  a one-to-many character -- best guess written; pick the right form in context.
  ²  a 02 (stable) match -- confirm it was not drifted to a regional form.
  ³  a 03 (change) match -- confirm the substitution fits.
At each position the longest match wins, trying tables 3, then 2, then 1. There is no phrase
dictionary, so an ambiguous character outside a 02/03 word is just marked ¹ (头发: 头->頭
silent, 发->發¹), which is why 汕头|发财 -> 汕頭發財 is caught, not mis-guessed as 汕頭髮財.

Review each mark: if right, delete it; if wrong, fix it and, when the case recurs, record it
(a word -> 02/03, a character rule -> prompt.md), then delete the mark.

Outputs under translations/Traditional Chinese/: the working <file>.tex (seeded once, then
preserved across runs so review edits survive; --force reseeds) and original/ (the /text
snapshot this draft was made from).

By default every .tex in /text is processed. Pass one or more file names to restrict the run
to just those files. File names may be bare (chapter_how.tex) or paths; only the basename is
used and it must exist in /text.

For an incremental update after /text changes, --update minimizes the work: it diffs each
original/ snapshot against the new /text source and re-converts (re-marks) ONLY the lines that
changed upstream, keeping the reviewed Traditional text everywhere else, then advances the
snapshot. So you resolve a handful of new marks in the changed regions instead of re-reviewing
the whole file. (A file whose working copy no longer matches its snapshot line-for-line can't
be spliced safely -- it is reported and left untouched for a manual merge or a --force reseed.)

Usage:
    python3 convert.py                         # convert all; keep existing working .tex
    python3 convert.py --force                 # reseed all working .tex from the script output
    python3 convert.py chapter_how.tex         # process only this file (keep it if it exists)
    python3 convert.py --force chapter_how.tex preface.tex   # reseed only these files
    python3 convert.py --update                # splice upstream changes into all files
    python3 convert.py --update chapter_how.tex             # ...into just this file
"""

import argparse
import csv
import difflib
import os
import shutil
import sys

MARK1, MARK2, MARK3 = "¹", "²", "³"   # table-1 (one-to-many char), table-2 (stable), table-3 (change)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
TEXT = os.path.join(ROOT, "text")
OUT = os.path.join(ROOT, "translations", "Traditional Chinese")


def load_chars(path):
    """Load 01_characters.csv -> {sc: (default_tc, ambiguous_bool)}. tc is one or more
    single-character candidates with no separator; the first is the default."""
    m = {}
    with open(path, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            sc = row["sc"]
            tc = row["tc"]
            if sc and tc:
                m[sc] = (tc[0], row.get("ambiguous", "") == "Y")
    return m


def load_vocab(path):
    """Load a hand-maintained sc,chosen table -> {sc: chosen}."""
    m = {}
    with open(path, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            sc = row["sc"].strip()
            chosen = row.get("chosen", "").strip()
            if sc and chosen:
                m[sc] = chosen
    return m


def convert(s, chars, stable, change):
    """Greedy longest-match conversion, tables 3 -> 2 -> 1. Returns (result, counts).
    Each non-trivial conversion is followed by its table's mark so the reviewer finds it
    inline; only a 1->1 single character is emitted with no mark."""
    maxvocab = max((len(k) for k in stable), default=0)
    maxvocab = max(maxvocab, max((len(k) for k in change), default=0))
    firsts = {k[0] for k in chars} | {k[0] for k in stable} | {k[0] for k in change}
    counts = {MARK1: 0, MARK2: 0, MARK3: 0}
    out = []
    i, n = 0, len(s)
    while i < n:
        c = s[i]
        if c not in firsts:                 # ASCII, spaces, punctuation -> passthrough
            out.append(c)
            i += 1
            continue
        hit = None                          # try a vocab phrase first: change (³) then stable (²)
        for length in range(min(maxvocab, n - i), 0, -1):
            seg = s[i:i + length]
            if seg in change:
                hit = (seg, change[seg], MARK3)
                break
            if seg in stable:
                hit = (seg, stable[seg], MARK2)
                break
        if hit is not None:
            seg, output, mark = hit
            out.append(output)
            out.append(mark)
            counts[mark] += 1
            i += len(seg)
            continue
        if c in chars:                      # fall back to a single character (table 1)
            default, ambiguous = chars[c]
            out.append(default)
            if ambiguous:                   # one-to-many -> review; 1->1 is silent
                out.append(MARK1)
                counts[MARK1] += 1
        else:
            out.append(c)                   # not in any table (rare): leave as-is
        i += 1
    return "".join(out), counts


def convert_quotes(s):
    r"""Rewrite LaTeX quotes to Traditional-Chinese corner brackets, nesting-aware.
    ``...'' -> 「...」, an inner `...' -> 『...』 (alternating by depth). A single ' is
    treated as a closing bracket ONLY when a `-opened single quote is on the stack, so
    English apostrophes (Fisher's, Ruth's) and math primes ($p_i'$) are preserved."""
    out, stack = [], []   # stack items: 'D' for a ``..'' level, 'S' for a `..' level
    i, n = 0, len(s)
    while i < n:
        two = s[i:i + 2]
        if two == "``":
            out.append("「" if len(stack) % 2 == 0 else "『")
            stack.append("D")
            i += 2
        elif two == "''" and stack and stack[-1] == "D":
            stack.pop()
            out.append("」" if len(stack) % 2 == 0 else "』")
            i += 2
        elif s[i] == "`":
            out.append("「" if len(stack) % 2 == 0 else "『")
            stack.append("S")
            i += 1
        elif s[i] == "'" and stack and stack[-1] == "S":
            stack.pop()
            out.append("」" if len(stack) % 2 == 0 else "』")
            i += 1
        else:
            out.append(s[i])
            i += 1
    return "".join(out)


def convert_full(text, chars, stable, change):
    """Full one-shot conversion of a source string: char map then quote rewrite."""
    result, _ = convert(text, chars, stable, change)
    return convert_quotes(result)


def splice_update(old_sc, new_sc, work_tc, chars, stable, change):
    """Diff the OLD Simplified source (the original/ snapshot) against the NEW one and splice:
    keep the reviewed Traditional line for every unchanged source line, and freshly convert
    (re-marking) only the source lines that changed or were inserted. Returns
    (merged_text, marks_added, status).

    The alignment key is the *Simplified* source, not the converted text -- resolving marks
    edited almost every Traditional line, so a 3-way merge on the converted text would treat
    every line as a human change. Diffing the source instead pinpoints exactly what moved
    upstream. This needs the working .tex to share its snapshot's line count (convert and
    mark-resolution are both line-preserving); if it does not, we report a mismatch and the
    caller leaves the file untouched for a manual merge or a --force reseed.
    """
    old = old_sc.splitlines(keepends=True)
    new = new_sc.splitlines(keepends=True)
    work = work_tc.splitlines(keepends=True)
    if len(old) != len(work):
        return None, 0, f"line-count mismatch (snapshot {len(old)} vs working {len(work)})"
    sm = difflib.SequenceMatcher(a=old, b=new, autojunk=False)
    out, marks = [], 0
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            out.extend(work[i1:i2])                          # unchanged source -> keep review
        elif tag in ("replace", "insert"):
            seg = convert_full("".join(new[j1:j2]), chars, stable, change)
            marks += sum(seg.count(m) for m in (MARK1, MARK2, MARK3))
            out.append(seg)                                  # changed source -> fresh + marked
        # "delete": the source lines are gone -> emit nothing
    return "".join(out), marks, "ok"


def main():
    ap = argparse.ArgumentParser(description="Convert /text (Simplified) toward Traditional Chinese.")
    ap.add_argument("--force", action="store_true",
                    help="reseed the working .tex from the script output (loses review edits)")
    ap.add_argument("--update", action="store_true",
                    help="splice in only what changed upstream: diff original/ vs /text and "
                         "re-mark just the changed lines, keeping the reviewed rest")
    ap.add_argument("files", nargs="*",
                    help="restrict to these /text .tex files (basename used); default: all")
    args = ap.parse_args()
    if args.force and args.update:
        sys.exit("error: --force and --update are mutually exclusive")

    tables = ("01_characters.csv", "02_vocab_stable.csv", "03_vocab_change.csv")
    for t in tables:
        if not os.path.isfile(os.path.join(HERE, t)):
            sys.exit(f"error: missing table {t}. Run tables/build_tables.py for 01; "
                     f"02/03 are hand-maintained.")

    chars = load_chars(os.path.join(HERE, "01_characters.csv"))
    stable = load_vocab(os.path.join(HERE, "02_vocab_stable.csv"))
    change = load_vocab(os.path.join(HERE, "03_vocab_change.csv"))

    all_tex = sorted(f for f in os.listdir(TEXT) if f.endswith(".tex"))
    if args.files:                                              # restrict to the named files
        tex_files = []
        for raw in args.files:
            name = os.path.basename(raw)
            if name not in all_tex:
                sys.exit(f"error: {name} is not a .tex file in {TEXT}")
            if name not in tex_files:
                tex_files.append(name)
    else:
        tex_files = all_tex
    os.makedirs(OUT, exist_ok=True)

    existing = [f for f in tex_files if os.path.isfile(os.path.join(OUT, f))]
    # reseed all targeted files when --force, or on a first/full run with nothing seeded yet
    reseed = args.force or (not args.files and not existing)

    orig = os.path.join(OUT, "original")                        # source-revision snapshot
    os.makedirs(orig, exist_ok=True)

    if args.update:
        update(tex_files, chars, stable, change, orig)
        return

    per_file = {}
    for name in tex_files:
        with open(os.path.join(TEXT, name), encoding="utf-8") as f:
            src = f.read()
        result, counts = convert(src, chars, stable, change)
        result = convert_quotes(result)
        per_file[name] = counts
        if reseed or not os.path.isfile(os.path.join(OUT, name)):
            with open(os.path.join(OUT, name), "w", encoding="utf-8") as f:
                f.write(result)
        shutil.copy2(os.path.join(TEXT, name), os.path.join(orig, name))   # snapshot this file

    report(tex_files, per_file, reseed, existing)


def update(tex_files, chars, stable, change, orig):
    """Incremental update: for each file, splice the upstream changes into the reviewed
    working .tex and re-mark only those, refreshing the snapshot. Files that can't be spliced
    safely (no working copy / no snapshot / line-count mismatch) are reported and left alone."""
    results = []   # (name, status, marks_added)
    for name in tex_files:
        work_path = os.path.join(OUT, name)
        snap_path = os.path.join(orig, name)
        new_path = os.path.join(TEXT, name)
        with open(new_path, encoding="utf-8") as f:
            new_sc = f.read()
        if not os.path.isfile(work_path) or not os.path.isfile(snap_path):
            # nothing reviewed to preserve -> seed it fresh and snapshot
            with open(work_path, "w", encoding="utf-8") as f:
                f.write(convert_full(new_sc, chars, stable, change))
            shutil.copy2(new_path, snap_path)
            results.append((name, "seeded (no prior review found)", None))
            continue
        old_sc = open(snap_path, encoding="utf-8").read()
        if old_sc == new_sc:
            results.append((name, "unchanged upstream", 0))
            continue
        work_tc = open(work_path, encoding="utf-8").read()
        merged, marks, status = splice_update(old_sc, new_sc, work_tc, chars, stable, change)
        if merged is None:
            results.append((name, f"SKIPPED -- {status}; reseed or merge by hand", None))
            continue
        with open(work_path, "w", encoding="utf-8") as f:
            f.write(merged)
        shutil.copy2(new_path, snap_path)                       # advance the snapshot
        results.append((name, "updated", marks))
    report_update(results)


def report_update(results):
    print(f"Update of {len(results)} file(s) in translations/Traditional Chinese/\n")
    total = 0
    for name, status, marks in results:
        tag = f"  {MARK1}{MARK2}{MARK3}+{marks}" if marks else ""
        if marks:
            total += marks
        print(f"    {name}: {status}{tag}")
    if total:
        print(f"\n{total} new mark(s) in the changed regions only -- the reviewed rest is "
              f"untouched.\nResolve them (confirm = delete the mark; fix + record durably "
              f"otherwise),\nthen build. The build fails while any {MARK1}{MARK2}{MARK3} remains.")
    else:
        print("\nNo new marks. (Files left as-is were unchanged, seeded, or skipped above.)")


def report(tex_files, per_file, reseed, existing):
    tot = {MARK1: 0, MARK2: 0, MARK3: 0}
    for counts in per_file.values():
        for k in tot:
            tot[k] += counts[k]
    total = sum(tot.values())

    print(f"Converted {len(tex_files)} file(s) into translations/Traditional Chinese/")
    if reseed:
        print("  working .tex seeded from the script output")
    else:
        print(f"  {len(existing)} working file(s) PRESERVED (review kept); use --force to reseed")
    print()
    print(f"{total} site(s) marked for review  "
          f"[{MARK1} one-to-many char: {tot[MARK1]}, "
          f"{MARK2} stable vocab: {tot[MARK2]}, "
          f"{MARK3} changed vocab: {tot[MARK3]}]")
    for name in tex_files:
        c = per_file.get(name, {})
        if c and sum(c.values()):
            print(f"    {name}: {MARK1}{c[MARK1]} {MARK2}{c[MARK2]} {MARK3}{c[MARK3]}")
    if total:
        print(f"\nReview every {MARK1}{MARK2}{MARK3}: confirm (delete the mark) or fix and record the")
        print("decision durably -- a kept/changed expression in 02_vocab_stable.csv /")
        print("03_vocab_change.csv, a character rule in prompt.md -- then delete the mark.")
        print("Also check the Traditional Chinese reads naturally (not merely de-simplified).")
        print(f"The build fails while any {MARK1}{MARK2}{MARK3} remains.")


if __name__ == "__main__":
    main()
