#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
build.py — full build script for the book (cross-platform: macOS / Linux / Windows).

It will:
  1. Locate the project root automatically (this script lives in scripts/, so the
     root is its parent directory).
  2. Generate a temporary latexmkrc on the fly (deleted afterwards) and compile
     with latexmk + xelatex.
  3. Name the output PDF after the book: the name comes from \bookname in
     text/config.tex (default "人妻约会指南"). For another language, just change
     \bookname in config.tex — e.g. set it to "人妻約會指南" and the output becomes
     "人妻約會指南.pdf", with no change to this script.
  4. Be "self-contained" by default: clean intermediate files before and after,
     leaving only that one PDF.

Usage (can be run from any directory):
    python scripts/build.py            self-contained build
    python scripts/build.py --keep      keep intermediates and build incrementally
On Windows, if `python` is unavailable, try `py scripts/build.py`.
"""
import argparse
import glob
import os
import platform
import re
import shutil
import subprocess
import sys
import tempfile

# Project root = the parent of this script's directory (scripts/)
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MAIN = "text/book.tex"        # main file (relative to root)
JOB = "book"                  # latexmk job name -> intermediates are all book.*
CONFIG = "text/config.tex"    # the book name is read from here
DEFAULT_NAME = "人妻约会指南"   # fallback output name (without extension) if config is unreadable

# ---- Colors: only on an interactive terminal; on Windows try to enable ANSI,
#      and fall back to plain text if that fails. ----
_color = sys.stdout.isatty()
if _color and platform.system() == "Windows":
    try:
        import ctypes
        h = ctypes.windll.kernel32.GetStdHandle(-11)          # STD_OUTPUT_HANDLE
        ctypes.windll.kernel32.SetConsoleMode(h, 7)           # ENABLE_VIRTUAL_TERMINAL_PROCESSING
    except Exception:
        _color = False


def _c(code):
    return code if _color else ""


GRN, RED, RST = _c("\033[32m"), _c("\033[31m"), _c("\033[0m")


def info(msg):
    print(f"{GRN}==>{RST} {msg}")


def err(msg):
    print(f"{RED}error:{RST} {msg}", file=sys.stderr)


def output_name():
    r"""Read \bookname from text/config.tex as the output name; fall back to default."""
    try:
        with open(os.path.join(ROOT, CONFIG), encoding="utf-8") as f:
            m = re.search(r"\\newcommand\*?\s*\{\\bookname\}\s*\{(.+?)\}", f.read())
            if m:
                return m.group(1).strip()
    except OSError:
        pass
    return DEFAULT_NAME


def tex_install_help():
    name = platform.system()
    if name == "Darwin":
        print("  macOS: install MacTeX (full distribution, includes latexmk and all packages):")
        print("      brew install --cask mactex      # or download from https://www.tug.org/mactex/")
        print("    Smaller option, BasicTeX: brew install --cask basictex")
        print("      (then: sudo tlmgr install latexmk ctex ccicons algorithm2e diagbox titlesec)")
    elif name == "Linux":
        print("  Linux:")
        print("    - Debian/Ubuntu:  sudo apt-get install texlive-full latexmk")
        print("    - Fedora:         sudo dnf install texlive-scheme-full")
    elif name == "Windows":
        print("  Windows: MiKTeX is recommended (auto-installs missing packages): https://miktex.org/download")
        print("    or TeX Live: https://www.tug.org/texlive/ (both include latexmk)")
    else:
        print("  Install TeX Live from https://www.tug.org/texlive/ (includes latexmk).")


def make_latexmkrc():
    """Generate a temporary latexmkrc (deleted after use) so latexmk uses xelatex."""
    fd, path = tempfile.mkstemp(prefix="latexmkrc-", suffix=".pl")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by scripts/build.py; removed after the build\n")
        f.write("$pdf_mode = 5;\n")                                    # 5 = xelatex
        f.write("$xelatex  = 'xelatex -interaction=nonstopmode %O %S';\n")
    return path


def clean():
    """Remove intermediate files (leaves the final PDF untouched)."""
    subprocess.run(["latexmk", "-c", MAIN],
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for f in glob.glob("text/*.aux"):              # .aux files \include creates under text/
        try:
            os.remove(f)
        except OSError:
            pass
    if os.path.exists(JOB + ".pdf"):               # intermediate PDF under the ASCII job name
        os.remove(JOB + ".pdf")


def main():
    parser = argparse.ArgumentParser(
        description="Build the book PDF with latexmk + xelatex.")
    parser.add_argument("--keep", action="store_true",
                        help="keep intermediate files and build incrementally (faster, for debugging)")
    args = parser.parse_args()

    os.chdir(ROOT)

    if not os.path.isfile(MAIN):
        err(f"cannot find {MAIN} under project root {ROOT}.")
        sys.exit(1)

    missing = [t for t in ("latexmk", "xelatex") if shutil.which(t) is None]
    if missing:
        err("not found: " + ", ".join(missing))
        tex_install_help()
        sys.exit(1)

    out_pdf = output_name() + ".pdf"
    rc = make_latexmkrc()
    try:
        if not args.keep:
            info("Cleaning old intermediate files...")
            clean()

        info("Building with latexmk (runs xelatex as many times as needed)...")
        code = subprocess.run(["latexmk", "-r", rc, MAIN]).returncode
        if code != 0:
            err(f"build failed; {JOB}.log was kept for inspection. If a package is missing:")
            print("  - TeX Live / MacTeX:  sudo tlmgr install <package>")
            print("  - MiKTeX (Windows):   usually auto-installs, or use the MiKTeX Console")
            sys.exit(1)

        if not os.path.exists(JOB + ".pdf"):
            err(f"build finished but {JOB}.pdf is missing; cannot produce {out_pdf}.")
            sys.exit(1)
        shutil.copyfile(JOB + ".pdf", out_pdf)     # produce the book-named final PDF

        if not args.keep:
            info("Cleaning intermediate files...")
            clean()

        info(f"Build complete! Output: {os.path.join(ROOT, out_pdf)}")
    finally:
        try:
            os.remove(rc)                          # delete the temporary latexmkrc
        except OSError:
            pass


if __name__ == "__main__":
    main()
